name: comment a SHASUM summary for each changed release

on:
  pull_request_target:
    branches: ["main"]

jobs:
  comment-summary:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: set base and head sha
        run: |
          echo "BASE_SHA=$(jq -r '.pull_request.base.sha' < "$GITHUB_EVENT_PATH")" >> $GITHUB_ENV
          echo "HEAD_SHA=$(jq -r '.pull_request.head.sha' < "$GITHUB_EVENT_PATH")" >> $GITHUB_ENV
      - name: show changed files
        run: |
          git show $BASE_SHA
          git show $HEAD_SHA
          git diff --no-commit-id --name-only $BASE_SHA..$HEAD_SHA
      - name: run shasum-summary
        run: python3 contrib/shasum-summary/main.py $BASE_SHA..$HEAD_SHA > comment
      - name: show comment
        run: cat comment
      - uses: actions/github-script@v7
        with:
          script: |
            const fs = require('fs');
            fs.readFile('comment', 'utf8', (err, comment) => {
              if (err) {
                console.error(err);
                return;
              }
              if (comment.length > 0) {
                github.rest.issues.createComment({
                  issue_number: context.issue.number,
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                  body: process.env.HEAD_SHA + "\n\n" + comment
                });
              }
            });
