name: comment a SHASUM summary for each changed release

on:
  pull_request_target:
    branches: [ "main" ]

jobs:
  comment-summary:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: show changed files
        run: |
          git show ${{ github.event.pull_request_target.base.sha }}
          git show ${{ github.event.pull_request_target.head.sha }}
          git diff --no-commit-id --name-only ${{ github.event.pull_request_target.base.sha }}..${{ github.event.pull_request_target.head.sha }}
      - name: run shasum-summary
        run: python3 contrib/shasum-summary/main.py ${{ github.event.pull_request_target.base.sha }}..${{ github.event.pull_request_target.head.sha }} > comment
      - name: show comment
        run: cat comment
      - uses: actions/github-script@v7
        with:
          script: |
            const fs = require('node:fs');
            fs.readFile('comment', 'utf8', (err, comment) => {
              if (err) {
                console.error(err);
                return;
              }
              if (comment.length > 0) {
                github.rest.issues.createComment({
                  issue_number: context.issue.number,
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                  body: "${{ github.event.pull_request_target.head.sha }}\n\n" + comment
                });
              }
            });
