name: comment a SHASUM summary for each changed release

on:
  pull_request_target:
    branches: [ "main" ]

permissions:
  pull-requests: write

jobs:
  comment-summary:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: show changed files
        run: git diff --no-commit-id --name-only ${{ github.event.pull_request.base.sha }}..${{ GITHUB_SHA }}
      - name: run shasum-summary
        run: python3 contrib/shasum-summary/main.py ${{ github.event.pull_request.base.sha }}..${{ GITHUB_SHA }} > comment
      - name: show comment
        run: cat comment
      - uses: marocchino/sticky-pull-request-comment@v2
        with:
          message: |
            "${{ GITHUB_SHA }}"
          path: comment
